## 1. 创建一个数组

In [1]:
import numpy as np
from narwhals import Int8

a = np.array([1, 2, 3, 4, 5.5])
print(a)

[1.  2.  3.  4.  5.5]


In [2]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
full = np.full((2, 2), 10)
print(full)

[[10 10]
 [10 10]]


In [6]:
eye = np.eye(5, 5, 2)
print(eye)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
arange = np.arange(0, 10, 2)
print(arange)
linspace = np.linspace(1, 10, 10)
print(linspace)

[0 2 4 6 8]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
# random = np.random.rand(3, 2, 2, 4)
# randn = np.random.randn(3,3)
# randint = np.random.randint(-10,-5 ,size = (3, 3))
choice = np.random.choice([1, 2, 3, 4], (5, 2))
# print(random)
# print(randn)
# print(randint)
print(choice)

[[1 2]
 [4 2]
 [2 2]
 [2 4]
 [4 4]]


In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.nbytes, a.T)
print(len(a))

[[1 2 3]
 [4 5 6]]
2 (2, 3) 6 int64 8 48 [[1 4]
 [2 5]
 [3 6]]
2


In [10]:
# a = np.array([0, 1, 2, 3, 4, 5])
# print(a[0], a[-1], a[2:5], a[::2], a[::-1])


b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)
# print(b.shape)
# print(b[0], b[0, 0], b[:, 0], b[1:, :2], b[b > 5])

mask = b > 5
print(mask)
print(b[mask])
b[mask] = 0
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[[1 2 3]
 [4 5 0]
 [0 0 0]]


In [11]:
a = np.arange(12)  # [0 1 2 3 4 5 6 7 8 9 10 11]
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
print(a.reshape(1, 2, 2, 3))

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]]


In [13]:
# 展平  # 从高维变为一维
# flatten 把原数据复制了一份, 然后在展平
b = a.flatten()
b[1] = 20
print(a)
print(b)
# ravel 直接在原数组的基础上进行了展平
c = a.ravel()
c[1] = 20
print(a)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0 20  2  3  4  5  6  7  8  9 10 11]
[ 0 20  2  3  4  5  6  7  8  9 10 11]
[ 0 20  2  3  4  5  6  7  8  9 10 11]


In [14]:
# 扩展维度
c = np.arange(6).reshape(2, 3)
print(c)
d = c[np.newaxis, :]  # 放到最前面, 就给最外层升一维
e = c[:, np.newaxis, :]  # 放到哪个维度后面, 就给哪个维度后面升一维
print(d)
print(e)
print(c.shape)
print(d.shape)
print(e.shape)

[[0 1 2]
 [3 4 5]]
[[[0 1 2]
  [3 4 5]]]
[[[0 1 2]]

 [[3 4 5]]]
(2, 3)
(1, 2, 3)
(2, 1, 3)


In [18]:
# 合并
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [9, 10, 11]])
print(a)  # (2,3,2)
print(b)  # (2,3,2)
print(np.vstack([a, b]))  # 垂直堆叠  分上下   (4,3,2)  # 第一个维度相加
print(np.hstack([a, b]))  # 水平堆叠  分左右   (2,3,4)  # 最后一个维度相加
print(np.concatenate([b, a], axis=0))  # (2,6)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [ 9 10 11]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]
[[ 1  2  3  7  8  9]
 [ 4  5  6  9 10 11]]
[[ 7  8  9]
 [ 9 10 11]
 [ 1  2  3]
 [ 4  5  6]]


In [19]:
# 分割
arr = np.arange(16).reshape(4, 4)
print(arr)
print(np.split(arr, 4, axis=1))  # (4,2)
print(np.hsplit(arr, 2))  # 水平

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [21]:
# # 数组的数学运算
a = np.array([[1, 2], [3, 4]])
# print(a)
# # 四则运算   对数组中每个元素都进行对应的运算规则
# print(a + 10)
# # 加减乘除都一样, 针对一个 常数
# print(a ** 2)  # 幂运算
# print(a / 2)  # 整除
# print(a // 2) # 取上的商  1 // 2
# print(a % 2)  # 取余

# 比较运算
b = a > 3
c = a == 3
print(b)
print(c)
print(np.sum(a > 3))  # 去看满足条件的数量, 也就是布尔矩阵中true的个数

[[False False]
 [False  True]]
[[False False]
 [ True False]]
1


In [23]:
a = np.array([1, 2, 3, 4, 5])
# 聚合函数
print(np.sum(a))        # 15
print(np.prod(a))       # 120（累积乘积）
print(np.min(a))        # 1
print(np.max(a))        # 5
print(np.mean(a))       # 3.0
print(np.median(a))     # 3.0
print(np.std(a))        # 1.41421356（标准差）
print(np.var(a))        # 2.0（方差）
print(np.cumsum(a))     # [ 1  3  6 10 15]（累积和）
print(np.cumprod(a))    # [  1   2   6  24 120]（累积积）

15
120
1
5
3.0
3.0
1.4142135623730951
2.0
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 逐元素乘法
print(A * B)
# [[ 5 12]
#  [21 32]]

# 矩阵乘法
print(np.matmul(A, B))
# [[19 22]
#  [43 50]]

# 或使用 @
print(A @ B)
# [[19 22]
#  [43 50]]

# 转置
print(A.T)
# [[1 3]
#  [2 4]]

# 逆矩阵
print(np.linalg.inv(A))
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 行列式
print(np.linalg.det(A))
# -2.0

# 特征值和特征向量
# 对于方阵A，如果存在非零向量v和标量λ，使得 A @ v = λ * v，
#  则λ称为A的特征值，v称为对应的特征向量。
#  几何含义：矩阵A作用在特征向量v上，只改变v的长度（缩放λ倍），不改变v的方向。

# 直观理解：
# A = [[1, 2],
#      [3, 4]]
# v1 ≈ [-0.824, -0.565]（对应 λ1=-0.372）：乘以A后被压缩反转，但方向不变
# v2 ≈ [-0.416,  0.909]（对应 λ2= 5.372）：乘以A后被拉长约5.37倍，方向不变

eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)   # [-0.37228132  5.37228132]
print(eigenvectors)
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]
# 每一列是一个特征向量：第1列对应λ1，第2列对应λ2
# 验证： eigenvalues[0] * eigenvectors[:,0]
# A @ eigenvectors[:,0]