## 1. 创建一个数组

In [2]:
import numpy as np
from narwhals import Int8

a = np.array([1, 2, 3, 4, 5.5])
print(a)

[1.  2.  3.  4.  5.5]


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
full = np.full((2, 2), 10)
print(full)

[[10 10]
 [10 10]]


In [21]:
eye = np.eye(5, 5, 2)
print(eye)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
arange = np.arange(0, 10, 2)
print(arange)
linspace = np.linspace(1, 10, 10)
print(linspace)

[0 2 4 6 8]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [41]:
# random = np.random.rand(3, 2, 2, 4)
# randn = np.random.randn(3,3)
# randint = np.random.randint(-10,-5 ,size = (3, 3))
choice = np.random.choice([1, 2, 3, 4], (5, 2))
# print(random)
# print(randn)
# print(randint)
print(choice)

[[2 1]
 [2 3]
 [4 1]
 [3 2]
 [4 1]]


In [48]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.nbytes, a.T)
print(len(a))

[[1 2 3]
 [4 5 6]]
2 (2, 3) 6 int64 8 48 [[1 4]
 [2 5]
 [3 6]]
2


In [56]:
# a = np.array([0, 1, 2, 3, 4, 5])
# print(a[0], a[-1], a[2:5], a[::2], a[::-1])


b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)
# print(b.shape)
# print(b[0], b[0, 0], b[:, 0], b[1:, :2], b[b > 5])

mask = b > 5
print(mask)
print(b[mask])
b[mask] = 0
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[[1 2 3]
 [4 5 0]
 [0 0 0]]
